name: Build and Test Water Quality Project

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest  # or macos-latest if you're targeting macOS
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install Qt manually (for Ubuntu)
    - name: Install Qt6
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential qt6-qmake qt6-base-dev qt6-charts-dev qt6-widgets-dev

    # Step 3: Install dependencies (e.g., build tools, Qt libraries)
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake

    # Step 4: Create build directory and run CMake to build the project
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    # Step 6: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: waterQuality-build
        path: build/
